### ISSUE TITLE
material design throws exceptions with multiple directives, no way to do templated values in loop

### ISSUE THREAD

**Issue by xenoterracide** [angular-translate/angular-translate#1157]
```
Error: [$compile:multidir] Multiple directives [mdTooltip (module: material.components.tooltip), translate (module: pascalprecht.translate)] asking for new/isolated scope on: <md-tooltip translate="">
http://errors.angularjs.org/1.4.3/$compile/multidir?p0=mdTooltip&p1=%20(module%3A%20material.components.tooltip)&p2=translate&p3=%20(module%3A%20pascalprecht.translate)&p4=new%2Fisolated<md-content flex="" ui-view="" id="content" class="ng-scope" data-ng-animate="1">cope&p5=%3Cmd-tooltip%20translate%3D%22%22%3E
    at REGEX_STRING_REGEXP (http://localhost:63342/mmp-player/app/bower_components/angular/angular.js:68:12)
    at assertNoDuplicate (http://localhost:63342/mmp-player/app/bower_components/angular/angular.js:8424:15)
    at applyDirectivesToNode (http://localhost:63342/mmp-player/app/bower_components/angular/angular.js:7803:15)
    at compileNodes (http://localhost:63342/mmp-player/app/bower_components/angular/angular.js:7459:15)
    at compile (http://localhost:63342/mmp-player/app/bower_components/angular/angular.js:7366:15)
    at applyDirectivesToNode (http://localhost:63342/mmp-player/app/bower_components/angular/angular.js:7856:33)
    at compileNodes (http://localhost:63342/mmp-player/app/bower_components/angular/angular.js:7459:15)
    at compileNodes (http://localhost:63342/mmp-player/app/bower_components/angular/angular.js:7471:15)
    at compileNodes (http://localhost:63342/mmp-player/app/bower_components/angular/angular.js:7471:15)
    at compileNodes (http://localhost:63342/mmp-player/app/bower_components/angular/angular.js:7471:15)
```
I would just use the filter, but I want to template a value from a loop in my translated string and I don't see any way to do that.

http://plnkr.co/edit/sxNjaZzQZT3hHH0QJsNA?p=preview

The commented out block will work except `letter` is empty in the translated string. 

     <md-list-item ng-repeat="artist in artists track by artist.name">
     ...
                <md-button aria-label="Play and add '{{artist.name}}' Station">
                    <md-tooltip><span translate="PLAY_BUTTON" translate-value-name="{{artist.name}}" /></md-tooltip>
                    <md-icon class="material-icons">play_arrow</md-icon>
                </md-button>
     ...

This offers a possible workaround, but I noticed another problem, I want to put the same translated string into the aria label.

**Comment by knalli** [comment]
@xenoterracide You should always inject non minified libs and use cdns in demo code to get the full debug code from AJS as well as better stacktraces.

What is wrong with this here? http://plnkr.co/edit/hvFtnzxwXNoXEnOjzMJr?p=preview

**Comment by xenoterracide** [comment]
yeah sorry, I only found links to the minified versions, and as with the stack I showed, I'm using bower.

in that the tooltip is just the letter, it does not use the text from translate.

**Comment by knalli** [comment]
If the directive does not provide refreshable bindings (here: tooltip), you will have to apply it manually. Perhaps you extend/decorate the existing directive with event listener (for translate refreshing) and apply the new texts on your own.

We cannot make this as we do not know the other library part.
