### ISSUE TITLE
compatibility with lodash 4

### ISSUE THREAD

**Issue by elmalto** [angular-translate/angular-translate#1363]
Hi,

upgrading to lodash 4.0.0 leads to the following angular-translate errors (for me):

angular: v1.4.8
angular-translate: v2.8.1
lodash: v4.0.0

```
TypeError: Cannot read property 'length' of undefined
    at $interpolate (http://localhost:9000/bower_components/angular/angular.js:11050:28)
    at Object.$translateInterpolator.interpolate (http://localhost:9000/bower_components/angular-translate/angular-translate.js:2526:28)
    at getFallbackTranslationInstant (http://localhost:9000/bower_components/angular-translate/angular-translate.js:1639:33)
    at getFallbackTranslationInstant (http://localhost:9000/bower_components/angular-translate/angular-translate.js:1641:20)
    at resolveForFallbackLanguageInstant (http://localhost:9000/bower_components/angular-translate/angular-translate.js:1733:20)
    at fallbackTranslationInstant (http://localhost:9000/bower_components/angular-translate/angular-translate.js:1764:16)
    at determineTranslationInstant (http://localhost:9000/bower_components/angular-translate/angular-translate.js:1855:22)
    at Function.$translate.instant (http://localhost:9000/bower_components/angular-translate/angular-translate.js:2294:24)
    at translateFilter (http://localhost:9000/bower_components/angular-translate/angular-translate.js:3098:23)
    at fn (eval at <anonymous> (http://localhost:9000/bower_components/angular/angular.js:13365:15), <anonymous>:4:76)
```

Have not been able to figure out what is causing this issue, but will investigate

**Comment by knalli** [comment]
Ehm.. @elmalto Thank you, but.. please be a little bit more specific.

* Which version of angular-translate you are using?
* Which version of angular you are using?
* What is the link to lodash? We have no dependency for this.

Well, as the error is thrown in AJS internally after invoking `$interpolate(string)(interpolationParams);`, I'm assuming there is some issue with the params in AJS internally. Either an issue by lodash or AJS. angular-translate is only providing an object.

**Comment by elmalto** [comment]
Sorry about this. Added versions, will create a plunkr asap. I added this here since angular-translate is the only dependency that is causing an issue

**Comment by TimonVS** [comment]
Any progress on this issue @elmalto?

**Comment by tspaeth** [comment]
Hm... taking  http://plnkr.co/edit/8J6SfdCqwY16lyzSoM2x?p=preview as an experimental base - I don't see an issue here?! Any details on a different setup you use?

**Comment by TimonVS** [comment]
This issue can be closed. We updated to Lodash 4 without any problems. And as @knalli mentioned, Angular Translate doesn't even have a dependency on Lodash.

**Comment by knalli** [comment]
Thank you for the note.
