### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sajan45** [angular-translate/angular-translate#1591]
I am using angular-translate for the first time. Even I am new to AngularJS.
So everything is working except I am getting some errors in browser console.
```
angular.js:13920 RangeError: Maximum call stack size exceeded
    at String.substr (native)
    at determineTranslationInstant (http://localhost/angular/ui-bootstrap/bower_components/angular-translate/angular-translate.js:1998:27)
    at determineTranslationInstant (http://localhost/angular/ui-bootstrap/bower_components/angular-translate/angular-translate.js:1999:22)
    at determineTranslationInstant (http://localhost/angular/ui-bootstrap/bower_components/angular-translate/angular-translate.js:1999:22)
    at determineTranslationInstant (http://localhost/angular/ui-bootstrap/bower_components/angular-translate/angular-translate.js:1999:22)
    at determineTranslationInstant (http://localhost/angular/ui-bootstrap/bower_components/angular-translate/angular-translate.js:1999:22)
    at determineTranslationInstant (http://localhost/angular/ui-bootstrap/bower_components/angular-translate/angular-translate.js:1999:22)
    at determineTranslationInstant (http://localhost/angular/ui-bootstrap/bower_components/angular-translate/angular-translate.js:1999:22)
    at determineTranslationInstant (http://localhost/angular/ui-bootstrap/bower_components/angular-translate/angular-translate.js:1999:22)
    at determineTranslationInstant (http://localhost/angular/ui-bootstrap/bower_components/angular-translate/angular-translate.js:1999:22)
```
I don't know what am I doing wrong. It happens when I use a dropdown to change language by calling `$translate.use(langKey)`. However it translates the page successfully. 

I have put the below lines in `config` for translation
```
$translateProvider.useSanitizeValueStrategy(null);
$translateProvider.useStaticFilesLoader({
  prefix: './languages/locale-',
  suffix: '.json'
});
$translateProvider
  .preferredLanguage('fr')
  .fallbackLanguage('en')
  .useStorage('translatorStorage');
```

Another problem I am facing which I am not sure is a issue or expected behaviour, i.e using custom storage successfully saves the key to `localStorage` as `NG_TRANSLATE_LANG_KEY` but whenever I reopen the page next time it does not use the saved language, instead saves the preferred language key to local storage and uses that language .

I am using: 
* angular-translate: 2.12.1
* version of angular: 1.5.8
* Chrome: 53.0

**Comment by tspaeth** [comment]
Please ask "how do I..." questions on Stackoverflow: http://stackoverflow.com/questions/tagged/angular-translate - you'll reach a bigger audience. Also, providing a complete example (as a Plunker) might help everybody to find the solution faster.

This issue tracker is mainly the feature-/bugtracker for angular-translate. But you're always free to add a feature request later on. 

Thanks.

**Comment by knalli** [comment]
Well, but a `Maximum call stack size exceeded` should not happen in our internal code.

@sajan45  Can you please provide a full example as described in our [issue template](https://github.com/angular-translate/angular-translate/blob/master/ISSUE_TEMPLATE.md)?

**Comment by sajan45** [comment]
Well, I found out that it was due to some improper linking of translation ids. So I will close this issue now.
Thanks for this amazing module and your quick response.
