### ISSUE TITLE
translate directive is not working with ngMessage directive

### ISSUE THREAD

**Issue by aikrez** [angular-translate/angular-translate#702]
The following is not working:

```
<div ng-message="max" translate="FORM.MAXVALUE"></div>
```

example: http://plnkr.co/edit/Zd590IhZrIugcvs9FZoQ?p=preview

TypeError: Cannot read property 'match' of undefined
    at Object.compile (http://localhost:63342/Angular/bower_components/angular-translate/angular-translate.js:773:56)
    at applyDirectivesToNode (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.0/angular.js:6765:32)
    at compileNodes (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.0/angular.js:6308:15)
    at compileNodes (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.0/angular.js:6320:15)
    at compile (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.0/angular.js:6230:15)
    at applyDirectivesToNode (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.0/angular.js:6678:33)
    at compileNodes (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.0/angular.js:6308:15)
    at compileNodes (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.0/angular.js:6320:15)
    at compileNodes (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.0/angular.js:6320:15)
    at compileNodes (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.0/angular.js:6320:15)

**Comment by johannesjo** [comment]
Is releated to this one https://github.com/angular-translate/angular-translate/issues/949#issuecomment-77576009
