### ISSUE TITLE
Fallback languages error

### ISSUE THREAD

**Issue by adi86** [angular-translate/angular-translate#798]
Hello I have problem with multiple language fallbacks... In my app language is determined in this order:

1. User personal settings
2. Browser settings
3. Default language

I set this up like this:

In app config section:

    var browserLang = navigator.languages ? navigator.languages[0] : navigator.language;

    $translateProvider.useStaticFilesLoader({
        prefix: '/public/languages/',
        suffix: '.json'
    });

    $translateProvider.fallbackLanguage([browserLang, 'en'])

    $translateProvider.preferredLanguage(browserLang);

    $translateProvider.use(browserLang);

Than when app is loaded user profile is loaded too, and i $watch user cultureType property for changes:

    $rootScope.$watch('UserData.CultureType', function(newD, oldD){
        if(newD !== oldD){
            $translate.preferredLanguage(newD);
            $translate.use(newD);
        }
    })

It works quite ok but when either user profile language and browser language are not available I get errors:
    TypeError: Cannot convert undefined or null to object
        at hasOwnProperty (native)
        at getFallbackTranslationInstant (http://localhost:3000/public/bower_components/angular-      translate/angular-translate.js:459:47)
        at resolveForFallbackLanguageInstant (http://localhost:3000/public/bower_components/angular-translate/angular-translate.js:494:22)
        at fallbackTranslationInstant (http://localhost:3000/public/bower_components/angular-translate/angular-translate.js:505:18)
    at determineTranslationInstant (http://localhost:3000/public/bower_components/angular-translate/angular-translate.js:552:24)
        at Function.$translate.instant     (http://localhost:3000/public/bower_components/angular-translate/angular-translate.js:728:26)
        at translateFilter (http://localhost:3000/public/bower_components/angular-translate/angular-translate.js:955:25)
        at $parseFilter (http://localhost:3000/public/bower_components/angular/angular.js:11942:14)
       at Scope.$eval (http://localhost:3000/public/bower_components/angular/angular.js:14123:28)
       at Object.watchExpression (<anonymous>:763:37) 

I am using Static Files Loader to load translation files...

**Comment by knalli** [comment]
Closing due inactivity.
